<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img class="first-slide" src="img/SANY0336.JPG" alt="slide">
      </div>
      <div class="item">
        <img class="second-slide" src="img/SANY0365.JPG" alt="slide">
      </div>
      <div class="item">
        <img class="second-slide" src="img/Expense-Claims-Automation-processes.png" alt="slide">
      </div>
      <div class="item">
        <img class="second-slide" src="img/4-big-reasons-to-automate-your-expense-management_302x640.jpg" alt="slide">
      </div>
    </div>
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
  <span class="icon-prev" aria-hidden="true"></span>
  <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
  <span class="icon-next" aria-hidden="true"></span>
  <span class="sr-only">Next</span>
  </a>
</div><!-- /.carousel -->



<?php


//{{ image("http://static.mywebsite.com/img/bg.png", false) }}
// echo Phalcon\Tag::image(array(
//  		"img/SANY0336.JPG",
//  		"class" => 'slide')
//  	); ?>